# Source - https://stackoverflow.com/a
# Posted by hoefling, modified by community. See post 'Timeline' for change history
# Retrieved 2026-01-03, License - CC BY-SA 4.0

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
